spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${client-id}
            client-secret: ${client-secret}
  credhub:
    url: https://credhub.service.cf.internal:8844/
    oauth2:
      registration-id: github
