spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${client-id}
            client-secret: ${client-secret}
  credhub:
    url: ${credhub-url}
    oauth2:
      registration-id: github
